#!/bin/sh
#--------configure--------------------
DIR=/home/dianqiuqiu
PROG=dianqiuqiu.py
LOGDIR=/home/dianqiuqiu/log
#unit:   second
INTERVAL=10
PARAMS=
#------------------------------------------------
 
start()
{
#----------------if PROG is down or lost, start it!
PRONUM=`ps aux | grep 'dianqiuqiu' |grep -v grep |wc -l`

if  test $PRONUM -lt 1
then
echo "------$PRONUM"
cd $DIR
(python3.5 dianqiuqiu.py &)
sleep 1
echo "`date`   PROCESSNUM LESS! or PROGRAM DOWN!" 1>>$LOGDIR/autocdp.log
echo "----START $PROG!----" 1>>$LOGDIR/autocdp.log
fi
}

#cd $DIR
#[[ -d $LOGDIR ]] || mkdir $LOGDIR

while test 1
do
start
sleep $INTERVAL
done
